### ISSUE TITLE
Contao Frontend-User Error

### ISSUE THREAD

**Issue by rflx** [netzmacht/contao-font-awesome#12]
Wenn sich ein Contao Frontend-User einloggt wenn Contao-Font-Awesome installiert ist, wird folgende Fehlermeldung ausgegeben:
```
Fatal error: Uncaught exception 'Exception' with message 'Invalid connection resource' in /home/public_html/system/modules/core/library/Contao/Database/Statement.php:87 Stack trace: 
#0 /home/public_html/system/modules/core/library/Contao/Database/Mysql.php(355): Contao\Database\Statement->__construct(Resource id #38, false) 
#1 /home/public_html/system/modules/core/library/Contao/Database.php(173): Contao\Database\Mysql->createStatement(Resource id #38, false) 
#2 /home/public_html/system/modules/core/classes/FrontendUser.php(94): Contao\Database->prepare('UPDATE tl_membe...') 
#3 [internal function]: Contao\FrontendUser->__destruct() 
#4 {main} thrown in /home/public_html/system/modules/core/library/Contao/Database/Statement.php on line 87
```
Könnt ihr das reproduzieren?

**Comment by dmolineus** [comment]
Kann ich nicht reproduzieren. Sicher, dass es an dieser Erweiterung liegt?

Der Fehler tritt auf, wenn irgendwo die Datenbank-Klasse instanziert wird bevor das User-Objekt erstellt wurde. Dann gibt es beim "Herunterfahren" des Systems diesen Fehler. Die Font Awesome Erweiterung greift aber nirgends aktiv auf die Datenbank zu, sodass der Fehler theoretisch nicht davon stammen kann.

**Comment by rflx** [comment]
Hi @dmolineus,
Sorry ich war etwas ungenau. Irgendwie wird die Fehlermeldung ausgegeben wenn ich contao-font-awesome mit theme-plus benutze. FontAwesome greift auf ThemePlus zu und diese auf die Datenbank.

**Comment by dmolineus** [comment]
Welche Version von Theme+ setzt du ein?

**Comment by rflx** [comment]
Theme+ 4.4.3 – habe aber scheibar noch das alte bit3/contao-theme-plus Repository.

**Comment by dmolineus** [comment]
Auch mit Theme+ kann ich es leider nicht nachstellen. Hast du noch andere Erweiterungen drin und kannst es durch Ausschluss-Verfahren der einzelnen Erweiterung eingrenzen?

**Comment by dmolineus** [comment]
Hab nochmal in den Code geschaut. Das Zusammenspiel beider Erweiterungen kann tatsächlich zu den beschriebenen Problem führen. Stelle in den nächsten Tagen einen Fix bereit. Wäre gut, dass du das dann testest, da ich es hier nicht nachvollziehen kann.

**Comment by rflx** [comment]
Kann ich gerne machen. Gib mir bitte bescheid wann du den Fix bereit hast.

**Comment by dmolineus** [comment]
Ich habe einen Fix im develop Branch bereitgestellt, implementiert in 5f55214f1b956d2eed0cc43bf76f4b7889556187. Bitte testen. In meinen Installationen tritt der Fehler so nicht auf.

**Comment by rflx** [comment]
Hi @dmolineus
Vielen Dank für deinen Fix. Mit der Version im develop Branch 5f55214 wird der Fehler nicht ausgegeben. In welcher Bugfix-Release planst du diesen Fix zu implementieren?

**Comment by dmolineus** [comment]
Ist als 4.3.0.2 released.
