### ISSUE TITLE
Contao Font Awesome prevents execution of Install Tool

### ISSUE THREAD

**Issue by fritzmg** [netzmacht/contao-font-awesome#13]
### Problem Description

While having the Contao Font Awesome Extension installed, you are unable to open the Install Tool, if you do not have an active backend login session.

### Reproduction

* Install Contao Font Awesome
* Log out of the backend
* Open `contao/install.php`
* You will be redirected to `contao/main.php`
* Log in to the backend
* Open `contao/install.php`
* Install Tool will work now

### Cause

The problem is [this line of code](https://github.com/netzmacht/contao-font-awesome/blob/master/src/Netzmacht/FontAwesome/FontAwesome.php#L66) of the Extension:
```php
\BackendUser::getInstance()->authenticate();
```
Within `FontAwesome::isActive`, which is called by `FontAwesome::initialize`, which is an `initializeSystem` hook. The `authenticate` function of `Contao\BackendUser` will __always__ redirect to `contao/`, if the user it __not__ logged in. See [BackendUser.php#L204](https://github.com/contao/core/blob/master/system/modules/core/classes/BackendUser.php#L204) ff.
```php
	public function authenticate()
	{
		// Do not redirect if authentication is successful
		if (parent::authenticate() || TL_SCRIPT == 'contao/index.php')
		{
			return;
		}
		$strRedirect = 'contao/';
		// Redirect to the last page visited upon login
		if (TL_SCRIPT == 'contao/main.php' || TL_SCRIPT == 'contao/preview.php')
		{
			$strRedirect .= '?referer=' . base64_encode(\Environment::get('request'));
		}
		\Controller::redirect($strRedirect);
	}
```
The `authenticate` function will only _not_ redirect, if the user is already logged in, or if the current script is `contao/index.php`. Thus, without an active login, you cannot reach the Install Tool (via `contao/install.php`), if this function happens to be called in an `initializeSystem` hook.

### Possible Solution

May be this actually requires a core change, if the call to `authenticate` is required by this extension, so that the first condition of `BackendUser::authenticate` also includes `TL_SCRIPT == 'contao/install.php'` (or `\Environment::get('script') == 'contao/install.php'` in Contao 3.2.x).

Alternatively, just return `false` in `isActive`, if the script is `contao/install.php`. I think the initialization of Contao Font Awesome is not necessary in the Install Tool?

**Comment by dmolineus** [comment]
I will deactive the initialization in for the install tool. It's only needed in the backend anyway.

Actually it would be nice that Contao would use a INSTALL mode for TL_MODE.

**Comment by fritzmg** [comment]
True. Contao 4 will have a better control over that, since it uses Symfony's scopes (see https://github.com/contao/core-bundle/blob/develop/DEPRECATED.md#constants ), but currently it still only has two scopes (Frontend and Backend), as far as I can see.
