### ISSUE TITLE
Source file does not exist in assets/components/

### ISSUE THREAD

**Issue by rflx** [netzmacht/contao-font-awesome#15]
Hi @dmolineus,
just came up with following issue when im selecting FontAwesome in the Layout panel:

```
Fatal error: Uncaught exception RuntimeException with message The source file "/assets/components/font-awesome/css/font-awesome.min.css" does not exist. thrown in composer/vendor/kriswallsmith/assetic/src/Assetic/Asset/FileAsset.php on line 73
```

The components folder `assets/components/` is empty. Don't know why, but composer successfully created FontAwesome's assets in `composer/vendor/components`.

contao 3.5.4
contao-font-awesome 4.4.0.1
contao-theme-plus 4.4.5

Cheers,
rflx

**Comment by dmolineus** [comment]
Package "robloach/component-installer" is responsible to install it in the right place. Somehow it doesn't work. 

Could you check your local `composer/composer.json` file? There should be a component dir directive.

```
"config": {
        "component-dir": "assets/components"
    }
```

You can try to reinstall the module. First remove contao-font-awesome, run update, add `robloach/component-installer` as explizit dependency and run update. Now install contao-font-awesome.

**Comment by rflx** [comment]
Hi @dmolineus 
I've checked my local `composer/composer.json` file. The component directive is set to 
```"config": {
        "component-dir": "../assets/components"
}```

Please note that there is another folder level (two dots). So therefore is no need to manually update the component directive in `composer/composer.json` if i reinstall the module with your hints?

**Comment by rflx** [comment]
I've tried to add `robloach/component-installer` as explizit dependency but its not solving the problem.

**Comment by dmolineus** [comment]
Do you have a folder `composer/vendor/contao/core` in that installation?

**Comment by rflx** [comment]
Nope.

**Comment by dmolineus** [comment]
Propably related to and caused by https://github.com/RobLoach/component-installer/issues/94
