### ISSUE TITLE
new release for FontAwesome 4.5

### ISSUE THREAD

**Issue by fritzmg** [netzmacht/contao-font-awesome#16]
Will there be a new release coming for FontAwesome 4.5 soon? I would need it especially because of the new Google Logo

* http://fortawesome.github.io/Font-Awesome/icon/google/
* http://fortawesome.github.io/Font-Awesome/icon/google-plus/

etc.

Of course I could update the fontawesome*.css manually in the meantime.

**Comment by dmolineus** [comment]
I just pushed the current state to the develop branch. It's should actually work but I haven't test it so far because of lack of time. Would be great if you can give me a feedback if everything works fine.

**Comment by fritzmg** [comment]
Hm, weird, I just noticed, that the new Google+ Icons should have been there in FontAwesome `4.4.0` as well. Though the font files provided with `netzmacht/contao-font-awesome` `4.4.0.1` didn't seem to have them.

**Comment by fritzmg** [comment]
> I just pushed the current state to the develop branch. It should actually work but I haven't test it so far because of lack of time. Would be great if you can give me a feedback if everything works fine.

Just tried with `netzmacht/contao-font-awesome: dev-develop` and everything seems to be in order :)

**Comment by dmolineus** [comment]
According to this post comment the icons got updated for 4.5: http://blog.fontawesome.io/2015/11/23/font-awesome-4.5-released/

If there are any issues with the provided files anyway, please create an issue at https://github.com/components/font-awesome as I just require the components package for it.

**Comment by fritzmg** [comment]
Ah ok, they only listed the new icons [here](http://fortawesome.github.io/Font-Awesome/whats-new/) not the updated ones - that's why I was confused.

Anyway, I did not detect any issues so far with the current dev branch.

**Comment by dmolineus** [comment]
Thx for testing. Just released it: https://github.com/netzmacht/contao-font-awesome/releases/tag/4.5.0
