### ISSUE TITLE
Font Awesome 5

### ISSUE THREAD

**Issue by dmolineus** [netzmacht/contao-font-awesome#20]

**Comment by dmolineus** [comment]
Atm there's no font awesome 5 installable using composer...

**Comment by fritzmg** [comment]
There is now :)

**Comment by dmolineus** [comment]
Yes, I know. The way font awesome 5 works requires some changes. At the moment only a plain icon is selected without style. This has to be changed. The icon wizard has to support it as well. I didn't have the time so far to work on a concept for v5.

**Comment by dmolineus** [comment]
There won't be a release for font awesome 5
