### ISSUE TITLE
Contao 4.5 Support

### ISSUE THREAD

**Issue by Olli** [netzmacht/contao-font-awesome#21]
Das Paket geht aktuell mit 4.5 nicht. Vermutlich liegt es an meta-palettes wenn ich den Log richtig interpretiere.
Danke 👍

**Comment by dmolineus** [comment]
Kannst du bitte den Log zur Verfügung stellen? Wo gibt es denn grundsätzlich Probleme? Bei der Installation, bei einer Funktionalität?

**Comment by Olli** [comment]
Der Log ist hier zu finden https://gist.github.com/Olli/4a925b083b0095918232954fb59a648a
Das Problem entsteht bei der Installation.

**Comment by dmolineus** [comment]
Okay, anscheinend hast du MetaPalettes 2.0.1 händisch installiert oder wird von einer anderen Erweiterung benötigt. Font Awesome ist derzeit noch nicht für MetaPalettes 2 freigegeben. 

Entweder MetaPalettes v1 installieren oder warten bis es gefixt ist. ;)

**Comment by Olli** [comment]
lt composer.lock wurde die 2.0er von Contao installiert. Ich habe die 1.10.0 händisch installiert und jetzt geht auch contao-font-awesome.
Danke 👍

**Comment by dmolineus** [comment]
Ich lasse das Ticket offen bis MetaPalettes v1 und v2 unterstützt wird.
